version: '3'
services:
  angular-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      - APOLLO_CLIENT_URI=https://public06b4f355ca14b171.stepzen.net/api/with-angular/__graphql
